<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630094258 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, image VARCHAR(500) DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_category_slug ON categories (slug) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE TABLE collections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, tagline VARCHAR(255) DEFAULT NULL, image VARCHAR(500) DEFAULT NULL, featured BOOLEAN DEFAULT false NOT NULL, sort_order INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_collection_slug ON collections (slug) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL, price INT NOT NULL, old_price INT DEFAULT NULL, on_sale BOOLEAN DEFAULT false NOT NULL, is_new BOOLEAN DEFAULT false NOT NULL, in_stock BOOLEAN DEFAULT true NOT NULL, free_delivery BOOLEAN DEFAULT true NOT NULL, warranty_years INT DEFAULT 2 NOT NULL, image VARCHAR(500) DEFAULT NULL, material VARCHAR(180) DEFAULT NULL, color VARCHAR(120) DEFAULT NULL, dimensions VARCHAR(120) DEFAULT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, collection_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B3BA5A5A12469DE2 ON products (category_id)');
        $this->addSql('CREATE INDEX IDX_B3BA5A5A514956FD ON products (collection_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_slug ON products (slug) WHERE (deleted_at IS NULL)');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A514956FD FOREIGN KEY (collection_id) REFERENCES collections (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5A12469DE2');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5A514956FD');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE collections');
        $this->addSql('DROP TABLE products');
    }
}
