<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630133409 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Move products.image into a product_images gallery table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE product_images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(500) NOT NULL, sort_order INT DEFAULT 0 NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8263FFCE4584665A ON product_images (product_id)');
        $this->addSql('CREATE INDEX idx_product_image_product ON product_images (product_id, sort_order)');
        $this->addSql('ALTER TABLE product_images ADD CONSTRAINT FK_8263FFCE4584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
        // Preserve existing single images as the primary (sort_order 0) gallery entry.
        $this->addSql('INSERT INTO product_images (product_id, url, sort_order) SELECT id, image, 0 FROM products WHERE image IS NOT NULL');
        $this->addSql('ALTER TABLE products DROP image');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE products ADD image VARCHAR(500) DEFAULT NULL');
        // Restore the primary image back onto the product.
        $this->addSql('UPDATE products p SET image = (SELECT pi.url FROM product_images pi WHERE pi.product_id = p.id ORDER BY pi.sort_order ASC, pi.id ASC LIMIT 1)');
        $this->addSql('ALTER TABLE product_images DROP CONSTRAINT FK_8263FFCE4584665A');
        $this->addSql('DROP TABLE product_images');
    }
}
