<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Introduces per-category spec attributes: creates category_attributes and
 * product_attribute_values, seeds the former Material/Rəng/Ölçü fixed fields as
 * default attributes on every category, migrates each product's values into the
 * new value table, then drops the old product columns.
 */
final class Version20260701213441 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Per-category product spec attributes (migrate material/color/dimensions)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE category_attributes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(120) NOT NULL, code VARCHAR(80) NOT NULL, type VARCHAR(20) DEFAULT \'text\' NOT NULL, unit VARCHAR(20) DEFAULT NULL, options JSON DEFAULT NULL, required BOOLEAN DEFAULT false NOT NULL, filterable BOOLEAN DEFAULT false NOT NULL, sort_order INT DEFAULT 0 NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1785CE0E12469DE2 ON category_attributes (category_id)');
        $this->addSql('CREATE INDEX idx_category_attribute_category ON category_attributes (category_id, sort_order)');
        $this->addSql('CREATE UNIQUE INDEX uniq_category_attribute_code ON category_attributes (category_id, code)');
        $this->addSql('CREATE TABLE product_attribute_values (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(500) NOT NULL, product_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_96CA0640B6E62EFA ON product_attribute_values (attribute_id)');
        $this->addSql('CREATE INDEX idx_product_attribute_value_product ON product_attribute_values (product_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_attribute_value ON product_attribute_values (product_id, attribute_id)');
        $this->addSql('ALTER TABLE category_attributes ADD CONSTRAINT FK_1785CE0E12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_attribute_values ADD CONSTRAINT FK_96CA06404584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_attribute_values ADD CONSTRAINT FK_96CA0640B6E62EFA FOREIGN KEY (attribute_id) REFERENCES category_attributes (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Seed the three default attributes on every category.
        $this->addSql("INSERT INTO category_attributes (category_id, label, code, type, required, filterable, sort_order) SELECT id, 'Material', 'material', 'text', false, true, 0 FROM categories");
        $this->addSql("INSERT INTO category_attributes (category_id, label, code, type, required, filterable, sort_order) SELECT id, 'Rəng', 'color', 'text', false, true, 1 FROM categories");
        $this->addSql("INSERT INTO category_attributes (category_id, label, code, type, required, filterable, sort_order) SELECT id, 'Ölçü', 'dimensions', 'text', false, false, 2 FROM categories");

        // Migrate each product's fixed fields into attribute values.
        foreach (['material', 'color', 'dimensions'] as $code) {
            $this->addSql(sprintf(
                "INSERT INTO product_attribute_values (product_id, attribute_id, value) SELECT p.id, ca.id, p.%s FROM products p JOIN category_attributes ca ON ca.category_id = p.category_id AND ca.code = '%s' WHERE p.%s IS NOT NULL AND p.%s <> ''",
                $code, $code, $code, $code,
            ));
        }

        $this->addSql('ALTER TABLE products DROP material');
        $this->addSql('ALTER TABLE products DROP color');
        $this->addSql('ALTER TABLE products DROP dimensions');
    }

    public function down(Schema $schema): void
    {
        // Restore the columns and copy values back before dropping the tables.
        $this->addSql('ALTER TABLE products ADD material VARCHAR(180) DEFAULT NULL');
        $this->addSql('ALTER TABLE products ADD color VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE products ADD dimensions VARCHAR(120) DEFAULT NULL');

        foreach (['material', 'color', 'dimensions'] as $code) {
            $this->addSql(sprintf(
                "UPDATE products p SET %s = v.value FROM product_attribute_values v JOIN category_attributes ca ON ca.id = v.attribute_id WHERE v.product_id = p.id AND ca.code = '%s'",
                $code, $code,
            ));
        }

        $this->addSql('ALTER TABLE category_attributes DROP CONSTRAINT FK_1785CE0E12469DE2');
        $this->addSql('ALTER TABLE product_attribute_values DROP CONSTRAINT FK_96CA06404584665A');
        $this->addSql('ALTER TABLE product_attribute_values DROP CONSTRAINT FK_96CA0640B6E62EFA');
        $this->addSql('DROP TABLE category_attributes');
        $this->addSql('DROP TABLE product_attribute_values');
    }
}
